source "https://rubygems.org"

ruby "2.1.1"

gem "rails", "4.1.0"
gem "neo4j", "3.0.0.alpha.6"
gem "unicorn"
gem "mutations"
gem "bcrypt", "~> 3.1.7"
gem "active_model_serializers"
gem "rack-cors", :require => "rack/cors"

gem "spring",        group: :development
gem "debugger", group: [:development, :test]
